#!/usr/bin/env bash
# Two things that must never reach a public commit, checked together.
#
#   scripts/sweeps.sh              # working tree + full commit history
#   scripts/sweeps.sh --tree-only  # skip the history walk (faster)
#
# Run by CI on every push, and worth running before any push that touches
# documentation.
#
# 1. ATTRIBUTION. Commits and files are authored by a person and say so. No
#    co-author trailers for tooling, no "generated with" lines, no robot
#    signature.
#
#    The patterns match TRAILERS AND SIGNATURES, not mentions: CONTRIBUTING.md
#    states the rule by naming the trailer, which a blunt grep for the words
#    would flag as a violation of itself. A gate that cannot tell a rule from a
#    breach of it gets disabled the first week, so this one anchors to line
#    start and to the exact signature forms.
#
# 2. PRIVACY. A sibling directory beside this repository holds personal
#    documents. It is deliberately outside the worktree and no tracked file may
#    name it or anything in it -- including in a commit message, which survives
#    a later deletion of the file.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

TREE_ONLY=0
[ "${1:-}" = "--tree-only" ] && TREE_ONLY=1

# This script contains every string it bans, because it is the definition of
# the rules. Grepping the whole tree therefore reports this file, every run,
# forever -- a gate that always fails is a gate that gets switched off. It is
# excluded by path, and by exactly one path, so a violation anywhere else is
# still caught.
SELF=':(exclude)scripts/sweeps.sh'

failures=0
report() {  # report <label> <grep output>
    if [ -n "$2" ]; then
        printf '  FAIL  %s\n' "$1"
        printf '%s\n' "$2" | sed 's/^/          /'
        failures=$((failures + 1))
    else
        printf '  pass  %s\n' "$1"
    fi
}

# Anchored to line start: a trailer is a line, a mention is not.
TRAILER='^[[:space:]]*(Co-authored-by|Co-Authored-By):'
# The two signature forms tooling appends, and the robot emoji that goes with
# one of them.
SIGNATURE='(Generated with \[|🤖 Generated|Generated by Claude Code)'

echo 'Attribution'
report 'no co-author trailers in tracked files' \
    "$(git grep -n -i -E "$TRAILER" -- . "$SELF" 2>/dev/null || true)"
report 'no generated-with signatures in tracked files' \
    "$(git grep -n -E "$SIGNATURE" -- . "$SELF" 2>/dev/null || true)"

if [ "$TREE_ONLY" = 0 ]; then
    # Commit messages are not rewritten by a later fix, so history is checked
    # too -- and it is checked across ALL refs, because a branch pushed once is
    # public whether or not it was merged.
    report 'no co-author trailers in commit messages' \
        "$(git log --all --format='%H %B' | grep -i -E "$TRAILER" || true)"
    report 'no generated-with signatures in commit messages' \
        "$(git log --all --format='%H %B' | grep -E "$SIGNATURE" || true)"
fi

echo
echo 'Privacy'
# The leading character class used to exclude '/' as well, to stop the pattern
# matching "adr/docs" or a URL path -- and in doing so it exempted exactly the
# forms a leaked reference is most likely to take: an absolute
# /Users/.../docs/ path, a relative ../docs/, a repo-relative java/docs/. Only
# a bare `docs/` at the start of a token was ever caught, which is the one form
# nobody writes by accident.
#
# So the class is narrower now and the URL case is handled where it actually
# occurs: a second pattern drops lines carrying a scheme. That is one
# understandable exemption instead of a silent hole, and the exemption is
# visible in the output when somebody needs to know why a line passed.
PRIVATE_DIR='(^|[^A-Za-z0-9_-])d[o]cs/'
ARTEFACTS='FINAL-HANDOVER|smit_cv|Claude Chat|interview/A[0-9]|iwebtechno'
# A URL path segment called docs is somebody else's repository, not this one's
# sibling. The load balancer controller's iam_policy.json lives under one.
URL_LINE='https?://'

# git ls-files rather than git grep here so the check covers a file's whole
# contents regardless of how git has it indexed.
report 'no reference to the private sibling directory' \
    "$(git ls-files -z -- . "$SELF" | xargs -0 grep -n -E "$PRIVATE_DIR" 2>/dev/null \
        | grep -v -E "$URL_LINE" || true)"
report 'no private artefact names' \
    "$(git grep -n -i -E "$ARTEFACTS" -- . "$SELF" 2>/dev/null || true)"
report 'nothing tracked under the private directory' \
    "$(git ls-files | grep '^d[o]cs/' || true)"

if [ "$TREE_ONLY" = 0 ]; then
    # The header of this script has always said the privacy rule covers commit
    # messages -- "including in a commit message, which survives a later
    # deletion of the file" -- and until now only the ATTRIBUTION rules were
    # actually checked there. A path named in a commit message is published the
    # moment the branch is pushed and is not removed by deleting the file it
    # named; rewriting history is the only fix, and it is much cheaper to catch
    # before the push.
    report 'no reference to the private directory in commit messages' \
        "$(git log --all --format='%H %B' | grep -E "$PRIVATE_DIR" \
            | grep -v -E "$URL_LINE" || true)"
    report 'no private artefact names in commit messages' \
        "$(git log --all --format='%H %B' | grep -i -E "$ARTEFACTS" || true)"
fi

echo
if [ "$failures" -eq 0 ]; then
    echo 'All sweeps pass.'
    exit 0
fi
printf '%d sweep(s) failed.\n' "$failures" >&2
exit 1
